### ISSUE TITLE
Não consigo usar a versao beta do vraptor-shiro com vraptor4-rc1

### ISSUE THREAD

**Issue by leodouglas** [dipold/vraptor-shiro#2]
Estou testando o vraptor4 rc1 e usei o vraptor-shiro beta1 e o metodo abaixo nao fica protegido:

```
@Get("/")
@Secured
@RequiresUser
public void index() {

}
```

**Comment by dipold** [comment]
@leodouglas Alguma mensagem de erro? Vc implementou as interfaces obrigatórias?

**Comment by leodouglas** [comment]
Sim, consegui declarando o interceptor no beans.xml

```
<interceptors>
    <class>br.com.caelum.vraptor.security.interceptor.SecurityInterceptor</class>
</interceptors>
```

**Comment by dipold** [comment]
Não há necessidade de declarar ele no beans.xml... pq ele já está declarado no beans.xml do projeto

**Comment by leodouglas** [comment]
sim eu reparei, mas no meu projeto eu precisei colocar no beans.xml do projeto.
Porque será?

**Comment by dipold** [comment]
A especificação diz que o beans.xml é valido para cada .jar então o problema deve ser alguma outra coisa...
Eu fechei o issue pq entendi que vc havia dito que agora está funcionando.. caso eu tenha entendido mal é só reabrir

**Comment by leodouglas** [comment]
Legal @dipold, deixa fechado se outra pessoa registrar o problema vc reabre ele. 
Pelo menos já fica registrado. :)
